version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(npm)"
      include: "scope"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/app/onchain"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "cargo"
    commit-message:
      prefix: "chore(cargo)"
      include: "scope"
    groups:
      cargo-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "pip"
    commit-message:
      prefix: "chore(pip)"
      include: "scope"
    groups:
      pip-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
